apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: web-demo
spec:
  components:
    - name: web-demo
      type: webservice
      properties:
        image: qms19/web-demo:latest
        port: 8080
      traits:
        - type: nocalhost
          properties:
            port: 8080
            gitUrl: https://github.com/qms19/web-demo.git
            image: go
            sync:
              type: sendReceive
            debug:
              remoteDebugPort: 9080